version: "3.9"

services:
  db:
    image: postgres
    container_name: db_toy_shop
    volumes:
      - db_toy_shop_vol:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  worker:
    restart: always
    build: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - webapp
    command: 'celery -A toy_shop worker -l info'

volumes:
  db_toy_shop_vol: