# Generated by Django 4.0.6 on 2022-08-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='author',
            new_name='user',
        ),
    ]
