# Generated by Django 4.0.6 on 2022-08-29 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_rename_author_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdialog',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_dialogs', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
