# Generated by Django 4.0.6 on 2022-08-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatdialog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdialog',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
