# Generated by Django 4.0.6 on 2022-08-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Коды', 'verbose_name_plural': 'Коды'},
        ),
    ]
