# Generated by Django 4.0.6 on 2022-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Постер'),
        ),
    ]
