# Generated by Django 4.0.6 on 2022-07-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='poster',
        ),
    ]
