# Generated by Django 4.0.6 on 2022-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.ImageField(upload_to='photos/', verbose_name='Постер'),
        ),
    ]
