# Generated by Django 4.0.6 on 2022-08-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0005_alter_product_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
