# Generated by Django 4.0.6 on 2022-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0006_remove_room_admin_remove_room_user_delete_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Постер'),
        ),
    ]
