# Generated by Django 4.0.6 on 2022-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toy_shop', '0007_alter_product_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение'),
        ),
    ]
