# Generated by Django 4.0.6 on 2022-08-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[(1, 'Оплата картой на сайте'), (2, 'Оплата картой при получении'), (3, 'Оплата наличными при получении')], default=1, max_length=10, verbose_name='переплет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='orders.order')),
            ],
        ),
    ]
