# Generated by Django 4.0.6 on 2022-08-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_postal_code_remove_order_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystatus',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Колличество'),
        ),
    ]
