# Generated by Django 4.0.6 on 2022-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paystatus_total_price_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystatus',
            name='order_status',
            field=models.CharField(choices=[('1', 'Принят'), ('2', 'Собран'), ('3', 'Передан курьеру'), ('4', 'Доставлен'), ('5', 'Аннулирован')], default='1', max_length=100, verbose_name='Статус оплаты'),
        ),
    ]
