# Generated by Django 4.0.6 on 2022-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_paystatus_order_status_orderitem_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('1', 'Принят'), ('2', 'Собран'), ('3', 'Передан курьеру'), ('4', 'Доставлен'), ('5', 'Аннулирован')], default='1', max_length=100, verbose_name='Статус Заказа'),
        ),
    ]
