# Generated by Django 4.0.6 on 2022-08-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitem_order_status_order_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Детали заказа', 'verbose_name_plural': 'Детали заказов'},
        ),
        migrations.AlterModelOptions(
            name='paystatus',
            options={'verbose_name': 'Статус оплаты', 'verbose_name_plural': 'Статусы оплаты'},
        ),
    ]
